services:
  app:
    build:
      context: .
    ports:
      - "9090:9090"
    environment:
      - POSTGRES_DSN=postgres://user:password@db:5432/mydb?sslmode=disable
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DB=0
      - SERVICE_ENVIRONMENT=dev
      - HTTP_SERVER_PORT=:9090
      - HOOK_CLIENT_URL=https://webhook.site/eb8a1637-0cfb-422c-adb3-8efcbd00443d
      - HOOK_CLIENT_SECRET=INS.me1x9uMcyYGlhKKQVPoc.bO3j9aZwRTOcA2Ywo
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    environment:
      REDIS_PASSWORD: redispassword
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
